AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.3
LineLength:
  Enabled: false
Layout/EmptyLineAfterMagicComment:
  StyleGuide: '#separate-magic-comments-from-code'
  Enabled: true
Metrics/AbcSize:
  Enabled: false
Style/StructInheritance:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/RedundantFreeze:
  Enabled: true
Metrics:
  Enabled: false
